/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js, but is committed here so typecheck works
// before the first local `next dev` run.
